app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime



@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

# Creating user

class User(UserMixin,db.Model):

    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    pass_secure = db.Column(db.String(255))
    password_hash = db.Column(db.String(255))
    bio = db.Column(db.String(255)) 
    profile_pic_path = db.Column(db.String())

    photos = db.relationship('PhotoProfile',backref = 'user',lazy = "dynamic")
    feedback = db.relationship('Feedback',backref = 'user',lazy = "dynamic")
    pitch = db.relationship('Pitch',backref = 'user',lazy = "dynamic")

    @property
    def password(self):
        raise AttributeError('You cannnot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)


    def save_user(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'User {self.username}'

class Pitch(UserMixin,db.Model):

    __tablename__ = 'pitch'
    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String(255))
    content = db.Column(db.String(255))
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
   
    def save_pitch(self):
        db.session.add(self)
        db.session.commit()
    def __repr__(self):
        return f'Pitch {self.content}'

class Feedback(UserMixin,db.Model):

    __tablename__ = 'feedback'

    id = db.Column(db.Integer,primary_key = True)
    image_path = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    

    def save_feedback(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_feedback(cls,id):

        feedback = Feedback.query.filter_by(feedback_id=id).all()
        return feedback


class PhotoProfile(db.Model):
    __tablename__ = 'profile_photos'

    id = db.Column(db.Integer,primary_key = True)
    pic_path = db.Column(db.String())
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,ValidationError
from wtforms.validators import Required,Email
#from .models import User

class PitchForm(FlaskForm):
    title = StringField('Pitch Title', validators=[Required()])
    pitch = TextAreaField('Add Pitch',validators=[Required()])
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):

    title = StringField('Review title',validators=[Required()])
    comment = TextAreaField('Pitch review', validators=[Required()])
    submit = SubmitField('Submit')



class FeedbackForm(FlaskForm):

    title = StringField('Feedback title',validators=[Required()])

    feedback = TextAreaField('Add feedback', validators=[Required()])

    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail


bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

photos = UploadSet('photos',IMAGES)

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    # configure UploadSet
    configure_uploads(app,photos)

    mail.init_app(app)




    # Will add the views and forms
    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # setting config
    return app
    

   

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)

from . import views

app/main/views.py
from flask import render_template, request, redirect, url_for, abort
from . import main
from ..models import User, Pitch,Feedback
from .forms import PitchForm,FeedbackForm,UpdateProfile
from .. import db,photos
from flask_login import login_user, logout_user, login_required, current_user
import datetime


# Views
@main.route('/')
def index():

    all=Pitch.query.all()
    '''
    View root page function that returns the index page and its data
    '''
    title = 'Home - Welcome to Pitch'

    form = PitchForm()
    return render_template('index.html',form = form,title=title, all=all,)
    

@main.route('/new_pitch', methods = ['GET','POST'])
@login_required
def new_pitch():
    form = PitchForm()

    if form.validate_on_submit():
        title = form.title.data
        content = form.pitch.data
        add_pitch = Pitch(title=title,content=content)
        add_pitch.save_pitch()
        return redirect(url_for('main.index'))
    return render_template('new_pitch.html',form=form)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/new_feedback', methods = ['GET','POST'])
@login_required
def new_feedback():
    form = FeedbackForm()
    pitch = Pitch.query.filter()
    if form.validate_on_submit():

        feedback = Feedback(title=form.title.data,feedback=form.feedback.data, pitch=pitch)
        db.session.add(feedback)
        db.session.commit()

    feed_back = Feedback.query.filter_by(pitch=pitch).all()
    return render_template('new_feedback.html',feed_back=feed_back,form=form)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/feedback.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

{{ wtf.quick_form(feedback) }}

{% for feedback in feed_back %}

<p>{{ feedback.feedback }}</p>
<p> By: {{feedback.title}}</p>

{% endfor %}

{% endblock %}

app/templates/index.html
{% extends 'base.html'%}

{% block content %}

<h3 style="font-weight:bolder"> Welcome user to Pitch, where you can pitch your ideas</h3>
{% if current_user.is_authenticated %}
{% for pitch in all %}
<p style="font-weight:lighter; font-size:20px">{{pitch.title}},{{pitch.content}}</p>

{% else %}
<p>Would you like to make a pitch? </p>
{% endfor %}
{%endif%}
{%endblock%}

app/templates/macros.html
{% macro displayMovieList(movie_list) %}

    {% for movie in movie_list %}
        <div class="col-xs-12 col-sm-4 col-md-2 col-lg-2 movie-card">
            <img src="{{ movie.poster }}" alt="{{ movie.title }} poster" class="img-responsive">
            <li class="text-center">
                <a href="/movie/{{movie.id}}">
                    {{ movie.title|truncate(10)}}</a>
            </li>
        </div>

    {% endfor %}
    {% endmacro %}
    <!-- Displaying reviews macro -->
{% macro displayReviews(review_list) %}
{% for review in review_list %}
<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 review-card">
    <h2> {{ review.title}} </h2>
    <p> {{ review.review | truncate(30) }}</p>
</div>
{% endfor %}


{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
          <br>
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> PITCH</a>
          </div>
          <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li><a href="{{url_for('main.profile',uname=current_user.username)}}">PROFILE</a></li>
            <li><a href="/">HOME</a></li>
            <li><a href="/new_pitch"> NEW PITCH</a></li>
            <!-- <li><a href="/new_feedback"> NEW FEEDBACK</a></li> -->
            <li><a href="{{url_for('auth.logout')}}">SIGN OUT</a></li>
            {% else %}
            <li><a href="{{url_for('auth.login')}}">SIGN IN</a></li>
            {%endif%}
          </ul>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">

          
      
          </div>
          <br>
        </div>
      </div>

app/templates/new_pitch.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
<div class="container">
     <div class="col-md-8">


  </div>

  <div class="col-md-4">

    {{ wtf.quick_form(form) }}
  </div>
</div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}
{% block content %}

<div class="container">

<div class="row">
  
  <!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>

    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}

    {% if user == current_user %}
      <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    {% endif %}

  </div>
  <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

    {%else%}
    <p>No profile picture</p>

    {% endif %}

      {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
      {% endif %}

    </form>
  </div>


</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'bootstrap/base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}